### PR TITLE
MAHOUT-1815: dsqDist(X,Y) and dsqDist(X) failing in flink tests.

### PR DESCRIPTION
**Pull request by andrewpalumbo**
After taking the Very long way around trying to repartition, etc., it turns out that the row just needed to be properly re-keyed.

Tests pass now.

Though we may want to re-examine the implementation of FlinkOpAtB, as it seems pretty inefficient.

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
This is a small fix so if there are no objections I'm just gonna push it.

**Comment by smarthi** [comment]
LGTM

**Comment by andrewpalumbo** [comment]
thx

**Comment by andrewpalumbo** [comment]
merged to flink-binding

**Pull request closed without merging**
