### PR TITLE
MAHOUT-2114 [WIP] Archive contains LICENSE and LICENSE.txt as well as NOTICE and NOTICE.txt

### PR DESCRIPTION
**Pull request by balashashanka**
### Purpose of PR:
Removing the file endings of NOTICE.txt LICENSE.txt to make sure file is not replicated

### Important ToDos
Please mark each with an "x"
- [x] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/mahout/]
- [x] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [x] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions? - NO

Is this the beginning of a larger project for which a feature branch should be made? - NO

### CODE REVIEW

**Comment by chrisdutz** [comment]
Looks good to me and should to the trick nicely.

**Comment by rawkintrevo** [comment]
Yea.. @balashashanka is this just WIP because no docs/licesnses/unit tests?  e.g. there's obviously a JIRA ticket for this- did you assign to yourself?

Assuming it is and you do, will merge this right after release (we're in code freeze rn)

**Comment by balashashanka** [comment]
Hi, yes the WIP is because of no docs and etc not done. And I dont seem to have permissions to assign the JIRA to myself.

**Comment by rawkintrevo** [comment]
ah yea- we turned that off bc we were having some issues with spam a while ago. I can assign to you or I can grant you permissions. Let me know which you prefer.

**Comment by balashashanka** [comment]
Anything would do, my JIRA username is "balaShashanka".

**Comment by rawkintrevo** [comment]
i granted you contributor rights @balashashanka . Thanks again for the contribution.

**Comment by andrewmusselman** [comment]
Thanks for the help Shashanka

**Pull request merged**
