### PR TITLE
MAHOUT-2000 [WIP] Added spark 2.2 profile

### PR DESCRIPTION
**Pull request by dustinvanstee**
Purpose of PR:

Adding Spark 2.2 to maven profile and adding it to travis CI for testing with this new version of Spark

Important ToDos

Please mark each with an "x"

 A JIRA ticket exists (if not, please create this first) Created unit tests where appropriate
NA  -  Added licenses correct on newly added files
x     -  Assigned JIRA to self
NA  - Added documentation in scala docs/java docs, and to website
Fail - Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by rawkintrevo** [comment]
@dustinvanstee looked good.  The 'gotchya' was Spark 2.2.0 officially dropped java 7 support, so those binaries are compiled with java8[1].  I found that out by googling the error in travis[2]

Because I'm curious- try changing [3] to `openjdk8` and see what happens. Will need further discusion about releasing Java8 for spark2 compatability on dev, but first lets see if it works.

[1] https://people.apache.org/~pwendell/spark-releases/latest/
[2] https://stackoverflow.com/questions/18161907/exception-in-thread-main-java-lang-unsupportedclassversionerror-unsupported-m
[3] https://github.com/apache/mahout/pull/332/files#diff-354f30a63fb0907d4ad57269548329e3R59

**Comment by rawkintrevo** [comment]
I checked that this does fail when trying to build with `-Pspark2.2` in Java7.  The error is non descript though, and it fails in Mahout Math.

**Comment by rawkintrevo** [comment]
It's looking good, could you squash your commits and give me a chance to look it over once more pls.

**Comment by dustinvanstee** [comment]
Closing this pull request and opening a new one.

**Pull request closed without merging**
