### PR TITLE
MAHOUT-2202 Testing Suite Template (plus MAHOUT-2207)

### PR DESCRIPTION
**Pull request by tdnaugle**
### Purpose of PR:
This PR implements a basic template for a testing suite using pytest, including the following items:
1. 	Adding pytest as a dependency
2. 	Define a helper function which can create from-scratch initial quantum state vectors (i.e. without using an instantiator from any of the backends), to be run as initial states for test circuits
3. 	Choose an example circuit to test on the qumat circuit execution and then on the backend native execution, followed by a comparison of the two final state vectors

I also implement a candidate solution for MAHOUT-2207 by simply upping the python requirement in poetry.toml: "^3.8" -> "^3.9"

### Important ToDos
Please mark each with an "x"
- [X] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/mahout/]
- [X] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [X] Created unit tests where appropriate
- [X] Added licenses correct on newly added files
- [X] Assigned JIRA to self
- [X] Added documentation in scala docs/java docs, and to website
- [X] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?
No

Is this the beginning of a larger project for which a feature branch should be made?
No

### CODE REVIEW

**Comment by rawkintrevo** [comment]
Just reviewed on community call. 

1. looks great
2. refactor to scale out to arbitrary number of backends
3. add minimal docs for 
   a. adding a new backend
   b. adding unit test to existing backend

**Comment by rawkintrevo** [comment]
@tdnaugle is this ready for another review?

**Comment by tdnaugle** [comment]
> @tdnaugle is this ready for another review?

Yes, this is ready.

**Comment by rawkintrevo** [comment]
Discussed on community call, clean up the git log, and merge. Will revisit issues on upcoming issues/PRs

**Pull request merged**
