### PR TITLE
MAHOUT-1655

### PR DESCRIPTION
**Pull request by pferrel**
Refactors mr-legacy into mahout-hdfs and mahout-mr

Compiles and completes unit tests, can launch spark-shell but doesn't run spark-itemsimilarity with the following error:

15/03/29 12:22:12 INFO AkkaUtils: Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@192.168.0.7:52857/user/HeartbeatReceiver
15/03/29 12:22:12 WARN BlockManager: Putting block broadcast_0 failed
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.hash.HashFunction.hashInt(I)Lcom/google/common/hash/HashCode;
	at org.apache.spark.util.collection.OpenHashSet.org$apache$spark$util$collection$OpenHashSet$$hashcode(OpenHashSet.scala:261)
	at org.apache.spark.util.collection.OpenHashSet$mcI$sp.getPos$mcI$sp(OpenHashSet.scala:165)
	at org.apache.spark.util.collection.OpenHashSet$mcI$sp.contains$mcI$sp(OpenHashSet.scala:102)
	at org.apache.spark.util.SizeEstimator$$anonfun$visitArray$2.apply$mcVI$sp(SizeEstimator.scala:214)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.util.SizeEstimator$.visitArray(SizeEstimator.scala:210)
	at org.apache.spark.util.SizeEstimator$.visitSingleObject(SizeEstimator.scala:169)
	at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate(SizeEstimator.scala:161)
	at org.apache.spark.util.SizeEstimator$.estimate(SizeEstimator.scala:155)
	at org.apache.spark.util.collection.SizeTracker$class.takeSample(SizeTracker.scala:78)
	at org.apache.spark.util.collection.SizeTracker$class.afterUpdate(SizeTracker.scala:70)
	at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:31)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:236)
	at org.apache.spark.storage.MemoryStore.putIterator(MemoryStore.scala:126)
	at org.apache.spark.storage.MemoryStore.putIterator(MemoryStore.scala:104)

### CODE REVIEW

**Comment by pferrel** [comment]
not sure where google.common is supposed t come from, looking...

**Comment by smarthi** [comment]
Its part of Guava.

**Comment by pferrel** [comment]
what is the status of guava in the rest of the project?

**Comment by andrewpalumbo** [comment]
It was in the mahout-math pom last i saw.

**Comment by smarthi** [comment]
Its still referenced in the parent pom with version 11.0.2.   Possible that
the offending class could be missing from this guava version ??

**Comment by andrewpalumbo** [comment]
no version number in the math-scala pom.

**Comment by smarthi** [comment]
r we not squashing the PRs before committing ??

**Comment by dlyubimov** [comment]
yeah. https://github.com/apache/mahout/commits/master.

we should not see "merged master" commits there (clear sign of not
squashing your personal PR history! )

**Pull request closed without merging**
