### PR TITLE
MAHOUT-1993: fix hardcoding of scala version in spark dependency-reduced.xml

### PR DESCRIPTION
**Pull request by andrewpalumbo**
### Purpose of PR:
Please give a short description of what this PR is for.

### Important ToDos
Please mark each with an "x"
- [x] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [x] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [x] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [x] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [x] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
to be committed on top of #326

**Comment by rawkintrevo** [comment]
squash and lgtm
(failed tests were re oracle7 no longer being supported by travis)

**Comment by andrewpalumbo** [comment]
Cool.. I'm at dr, and won't be back for a little while.  If u r working on this now and need to push , please feel free to push.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by andrewpalumbo** [comment]
committed in a799ead59aa77cab0596f72bbe40872b59367e35

**Pull request closed without merging**
