### PR TITLE
MAHOUT-1706: remove dependency jars from /lib in the binary distribution

### PR DESCRIPTION
**Pull request by andrewpalumbo**
The mahout distribution currently is shipping ~56 MB of dependecy jars in the /lib directory of the distribution.   These are only added to the classpath by /bin/mahout in the binary distribution. It seems that we can remove them from the distribution. (we need to get the size of the distribution down)

Any input is appreciated.

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
Closing this PR (against master).  Will re-open it against the 0.10.x branch.  This still needs testing on a cluster.

**Comment by smarthi** [comment]
Try running this thru 

`mvn -Pmahout-release,apache-release,hadoop2 package`

to ensure that the build goes thru fine and verify the size of the artifacts in /target after this.

**Comment by smarthi** [comment]
Is this good to merge ?

**Comment by andrewmusselman** [comment]
Where is this, merge or no?

**Comment by andrewpalumbo** [comment]
I just reopened it this PR after discussion last week.  Haven't had a chance to test it yet.

**Comment by andrewpalumbo** [comment]
The source builds and tests fine for me locally (Travis can't handle the mr tests).  This really needs to be tested on a (pseudo)-cluster after being built with: 
`mvn -Pmahout-release,apache-release,hadoop2 package`
for both binary and source releases.

**Comment by andrewmusselman** [comment]
I'll take it for a spin.

**Comment by rawkintrevo** [comment]
Close or merge (or stand by?)

**Comment by andrewpalumbo** [comment]
Let's hold off on this until 0.13.1.. it will mean much more testing.. only wins us a bit of space.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by rawkintrevo** [comment]
Let's push forward on this quickly if possible.

**Comment by rawkintrevo** [comment]
still want to try to sneak this in for 0.13.1?

**Pull request closed without merging**
