### PR TITLE
[BF] [WiP] MAHOUT - 1973

### PR DESCRIPTION
**Pull request by AdityaAS**
### Purpose of PR:
Duplicate of PR #321.
I had a syncing issue between the original repo and my forked repo. Deleted and reforked AdityaAS/mahout. Hopefully, next time I'll learn how to deal with the issue without deleting and reforking.

@rawkintrevo @andrewpalumbo  Please delete the old PR.
Please give a short description of what this PR is for.

### Important ToDos
Please mark each with an "x"
- [ x] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [x ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ x] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [ ] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by AdityaAS** [comment]
@rawkintrevo viennacl seems to build fine now. Building the flink profile however, throws the error "/home/aditya/mahout/flink/src/test/scala/org/apache/mahout/flinkbindings/standard/ClusteringSuite.scala:25: error: not found: type ClusteringSuiteBase
[ERROR]   with DistributedFlinkSuite with ClusteringSuiteBase"

**Comment by rawkintrevo** [comment]
lgtm

**Comment by andrewpalumbo** [comment]
re: `ClusteringBaseSuite`, it should not be in the build, and could be failing for other reasons- last i checked it was out of date, but compatible with Hadoop 2.  the `ClusteringSuiteBase` seems like it was committed in c29496cb11372baddbb76acdee51530347525645 so it may need to be extended for `flink`.

**Comment by andrewpalumbo** [comment]
^^ otherwise lgtm

**Comment by AdityaAS** [comment]
@andrewpalumbo I didn't quite get what you said.

**Pull request closed without merging**
