### PR TITLE
MAHOUT-2007 Fix wikipedia xml dump url in examples

### PR DESCRIPTION
**Pull request by jackcgai**
### Purpose of PR:
Please give a short description of what this PR is for.
MAHOUT-2007 Fix wikipedia xml dump url in examples

### Important ToDos
Please mark each with an "x"
- [x ] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [x ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [x ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [x ] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?
no
Is this the beginning of a larger project for which a feature branch should be made?
no

### CODE REVIEW

**Comment by rawkintrevo** [comment]
@jackcgai thanks for the contribution!

Sorry for long delay in review. 

LGTM

**Comment by jackcgai** [comment]
Thank you @rawkintrevo !

**Comment by jackcgai** [comment]
I re-open the pull request for others to review.

**Comment by andrewpalumbo** [comment]
Thanks @jack.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Pull request closed without merging**
