### PR TITLE
Corrections to README.md: Made grammatical, punctuation corrections in the README.md file to ma…

### PR DESCRIPTION
**Pull request by royadityak94**
…ke the text robust, grammar-proof

Applied grammatical corrections throughout the README.md files at several places to avoid the confusion arising from incorrect punctuations, grammatical.

### Purpose of PR:
Updated README.md file getting rid of incorrect grammatical and punctuations.

### Important ToDos
Please mark each with an "x"
- [ ] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/mahout/]
- [ ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [x] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by rawkintrevo** [comment]
thank @royadityak94 for the contribution. 

Out of curiosity- did you check that the information in that README is still technically valid? (we just did a major refactor, and I'm not sure all the docs are caught up). 

I only ask bc if it is not- we need to tag it for update. 

Other than that, lgtm- but will wait for your response for a couple days so you don't miss my question on a closed PR.

**Comment by royadityak94** [comment]
@rawkintrevo Thanks for reaching out. The README file may have to be updated to match the recent refactoring, but what this commit lends is a grammatical, punctuation correction on the last version of the README file. 
What I will suggest is that you should approve this PR and the revision work may be accomplished in the development phase. Btw, I would like to continue the README update and would very much wish to pick that story.

**Comment by rawkintrevo** [comment]
Cool- I'm going to merge this now then. Can you create JIRA tickets? [1]. Ideally- create an issue on there then in the future start a PR with MAHOUT-XXX (where XXXX will be your ticket number). 


[1] https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=80

**Comment by andrewmusselman** [comment]
Thanks for your contribution @royadityak94! Could you create an issue in JIRA so we can track this?

**Pull request merged**
