### PR TITLE
Mahout 1981 - Front End Design Update

### PR DESCRIPTION
**Pull request by davidtmiller**
### Purpose of PR:
Please give a short description of what this PR is for.

### Important ToDos
Please mark each with an "x"
- [ ] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [ ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [ ] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by rawkintrevo** [comment]
This is awesome.  Thank you!!

My vote is to merge this to a feature branch, clean it up / merge it with master / squash / straighten out the docs, then merge to master.

@dustinvanstee @andrewpalumbo @andrewmusselman @pferrel

**Comment by andrewpalumbo** [comment]
+1 on merging and cleaning up from there.

**Comment by rawkintrevo** [comment]
Merged this to apache/mahout/mahout-1981 @davidtmiller you can close.

**Comment by andrewpalumbo** [comment]
thank you, @davidtmiller!

**Comment by rawkintrevo** [comment]
mark this for closing June 13, 2018

**Pull request closed without merging**
