### PR TITLE
MAHOUT-2024  Update doap_Mahout.rdf

### PR DESCRIPTION
**Pull request by jackcgai**
### Purpose of PR:
Please give a short description of what this PR is for.
Update the doap_Mahout.rdf file to the current most recent release.

### Important ToDos
Please mark each with an "x"
- [x] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [x] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [x ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [x] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?
no
Is this the beginning of a larger project for which a feature branch should be made?
no

### CODE REVIEW

**Comment by rawkintrevo** [comment]
can you squash into one commit pls? ott lgtm.

**Comment by rawkintrevo** [comment]
and thanks for the contrib!!

**Comment by rawkintrevo** [comment]
hey jack, please create a branch for this with 
`git checkout -b mahout-2024`

Then squash into one commit with 
`git rebase -i HEAD~2`

For more info see:
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by jackcgai** [comment]
Hi @rawkintrevo, thanks for direction. Done.

**Comment by rawkintrevo** [comment]
Hey @jackcgai you still have 2 commits- I'm not 100% sure what happened. I think you accidently got `[maven-release-plugin] prepare for next development iteration` mixed in by mistake.  

I'm going to email you offline, maybe we can get together on hangout or something and get the commit thing worked out. OTT, this lgtm- and I plan on doing so once the "PR is right"

**Comment by rawkintrevo** [comment]
@jackcgai i merged but forgot to close- please go ahead and do that.
thx!

**Comment by jackcgai** [comment]
@rawkintrevo Thank you!

**Pull request closed without merging**
