### PR TITLE
MAHOUT-1833 - Enhance svec function to accept cardinality as parameter

### PR DESCRIPTION
**Pull request by resec**
### What is this PR for?
Enhance the existing svec function to accept cardinality as parameter(with default value defined), so user can specify the created vector size they want.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Add the cardinality parameter to svec with default value defined
* [x] - Add test case to MathSuite
* [ ] - Update any doc if needed(pending to check)

### What is the Jira issue?
* [MAHOUT-1833](https://issues.apache.org/jira/browse/MAHOUT-1833)

### How should this be tested?
1. Clone the code into local
2. Maven build and test, all tests should be green

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Pending to check

### CODE REVIEW

**Comment by resec** [comment]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project mahout-mr: ExecutionException: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/apache/mahout/mr && /usr/lib/jvm/java-7-oracle/jre/bin/java -Djava.security.auth.login.config=/home/travis/build/apache/mahout/mr/target/../../buildtools/src/test/resources/jaas.config -jar /home/travis/build/apache/mahout/mr/target/surefire/surefirebooter4383272596373359636.jar /home/travis/build/apache/mahout/mr/target/surefire/surefire2790607970252828964tmp /home/travis/build/apache/mahout/mr/target/surefire/surefire_1681133930090970673085tmp`

The Travis CI failed for some strange reason here, any help?

**Comment by smarthi** [comment]
Ignore the travis failures, its still WIP.  Thanks for the PR, we'll merge it soon for the next release.

**Comment by dlyubimov** [comment]
conceptually +1

**Comment by resec** [comment]
I cannot find any doc to update(but is it not a bad thing?), so I am assuming that there is no doc for this PR to update, please do let me know if I missed anything.

**Comment by dlyubimov** [comment]
@resec there's authoritative, sort of, original doc in this branch. https://github.com/apache/mahout/tree/gh-pages/doc

You may take it and submit a PR to it (it requires lyx/latex editor, assuming you are on ubuntu).

Good thing is that you can take it and modify it with a usual pull request process.

Bad things about doing it that way are that, first, it is sort of an authored document I originally contributed from elsewhere (I can remove any attributions if really becomes community-maintained). 

But the real reason is, secondly, currently it really being migrated to ASF CMS, and it needs to be changed here : http://mahout.apache.org/users/environment/in-core-reference.html which requires apache committer status. 

So you really would need to change ASF CMS page and if you don't have privileges to do it, somebody would have to do it on your behalf after this PR is in.

**Comment by resec** [comment]
@dlyubimov, thanks for the great detailed explanation.

I think I don't have privileges to edit this [In Core Reference Page](http://mahout.apache.org/users/environment/in-core-reference.html), so I guess somebody may need to help.

And for the authoritative doc in another branch, I think I can help, will submit another PR accordingly soon.

**Comment by andrewpalumbo** [comment]
@resec  as far as updating the  "In Core Reference Page" if its a short addition, It may be easiest to just add the text to your JIRA (or here on the PR) that way one of us can just make the addition.

This looks good to me +1 to commit this.

**Comment by andrewpalumbo** [comment]
It would be good to have @dlyubimov sign off of this.

**Comment by dlyubimov** [comment]
i am +1 contingent on all tests working.

**Comment by andrewpalumbo** [comment]
thx.  The PR was opened wile we were configuring Travis.  I'll test it locally and commit it later.

**Comment by resec** [comment]
@andrewpalumbo

Thanks for your help and sorry for this late responding, it has been busy days.

Let me provide the doc amendment here.

In [Mahout-Samsara's In-Core Linear Algebra DSL Reference](http://mahout.apache.org/users/environment/in-core-reference.html), in session `[Inline initalization]` -> `[Sparse vectors]`, we can add below to the end of it:

```
// to create a vector with specific cardinality
val sparseVec1 = svec((5 -> 1.0) :: (10 -> 2.0) :: Nil, cardinality=20)
```

In the [Mahout Scala Bindings and Mahout Spark Bindings for Linear Algebra Subroutines](http://mahout.apache.org/users/sparkbindings/ScalaSparkBindings.pdf), in session 1.2 `[Inline initialization]`, we can add the same thing as shown above.

**Comment by andrewpalumbo** [comment]
no problem,  Thanks for the contribution, @resec!  I've updated http://mahout.apache.org/users/environment/in-core-reference.html to show this feature.  

Please note that http://mahout.apache.org/users/sparkbindings/ScalaSparkBindings.pdf is a different document than @dlyubimov pointed out above, and i can not edit that.

I believe that you meant this doc: https://github.com/apache/mahout/tree/gh-pages/doc

I will update that  when I get a chance, If you have not already made a PR against it.  

Thanks.

**Pull request closed without merging**
