### PR TITLE
An alternative scaling method for Baum Welch for HMM.

### PR DESCRIPTION
**Pull request by manognavemulapati**
This implements an alternative scaling method (called rescaling) for Baum Welch algorithm for unsupervised HMM training. The new scaling method partially addresses Mahout-627. The existing scaling method  based on log scaling is not numerically stable when tried with the Mapreduce version of Baum Welch proposed for Mahout-627. With the rescaling method, I am able to successfully run the Mapreduce version of Baum Welch on long training sequences. Further details and references are given in the following writeup.
Implementation of an Alternative Scaling for Baum-Welch Algorithm for Hidden Markov Model (HMM) in Apache Mahout -- http://manognavemulapati.github.io/mahout/HMMScaling.pdf.

### CODE REVIEW

**Comment by dlyubimov** [comment]
MR, not sure we still take it

**Comment by dlyubimov** [comment]
Or this is an in-memory implementation?

**Comment by manognavemulapati** [comment]
Yes this is MR based implementation. If MR may not be acceptable, will it be considered for Mahout if the project is rewritten for Spark?

**Comment by dlyubimov** [comment]
Not likely

Only if it is rewritten for Samsara.

On Wed, Mar 9, 2016 at 7:49 PM, Manogna Vemulapati <notifications@github.com

**Comment by dlyubimov** [comment]
@manognavemulapati I did not want to discourage you. Small clarification: Samsara algebra and Scala should be dominant with code, which then will be able to run accross a range of backends (Spark including). there's a number of resources on it as well as a book. Hope this helps.

**Comment by andrewmusselman** [comment]
@manognavemulapati any interest in continuing, possibly writing a comparable HMM impl in Samsara?

**Comment by andrewmusselman** [comment]
@manognavemulapati Hey, saw your latest commit; would you be interested in working on converting this to the newer framework? Don't want to see you keep going on something we're not likely to include in the project.

**Comment by manognavemulapati** [comment]
Yes, I intend to convert this project to a Samsara implementation -- I'm
still learning the new framework.

**Comment by andrewpalumbo** [comment]
@manognavemulapati This is great to see coming along into samsarsa.  Could you please start a ticket for it on mahout JIRA:  https://issues.apache.org/jira/projects/MAHOUT/summary ?

As well It will make it much easier for reviewers to follow if you add a message summary of what you've done in each commit:

E.g:  `git commit -am "Add Expected Number of Emissions Method"` 

As well we do have a fit/predict framework that you'll eventually want to refactor this into:   

https://github.com/apache/mahout/tree/master/math-scala/src/main/scala/org/apache/mahout/math/algorithms

Thanks- Great to see this work!

**Comment by svidovich** [comment]
Wow!

**Pull request closed without merging**
