### PR TITLE
MAHOUT-2067: Update RAT plugin to latest release version.

### PR DESCRIPTION
**Pull request by ottlinger**
### Purpose of PR:
Please give a short description of what this PR is for.
Update to latest RAT version 0.13

### Important ToDos
Please mark each with an "x"
- [X] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/MAHOUT/]
- [ ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ ] Assigned JIRA to self (not possible due to insufficient rights)
- [ ] Added documentation in scala docs/java docs, and to website
- [ ] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions? n

Is this the beginning of a larger project for which a feature branch should be made? n

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
lgtm pending  tests.

**Comment by ottlinger** [comment]
@andrewpalumbo - thanks for taking a look and sorry for the many commits. I hope stuff can be merged now.

**Comment by andrewpalumbo** [comment]
thanks for the contribution @ottlinger! i'm actually giving a version bump in the poms right now to `14.0` just FYI.

**Comment by ottlinger** [comment]
The ASF parent reference looks quite old and a lot of maven plugins, maybe this has something to do with the problems that were mentioned on builds@apache.org

**Comment by andrewpalumbo** [comment]
Merging now, Thanks again @ottlinger,  Yes I was just looking at the parent and it is v.17 . seems to be a bit old.  do you know what version most projects are using these days?

**Comment by ottlinger** [comment]
@andrewpalumbo someone merged out my changes as they are not available on current head - can you reapply my changes. I'm happy that many people suggested to update the plugins.
Personally I'd use the latest version if that's fine with your compiler (language level) settings. 

Thanks

**Pull request merged**
