### PR TITLE
MAHOUT-1841 change UNIFORM_DIVISOR to 2^63 from 2^64

### PR DESCRIPTION
**Pull request by andrewpalumbo**
Matrices.SymmetricUniformView is returning numbers on the range of (-.5,.5).  Documentation calls for [1,1).

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
@smarthi this seems to pass all tests for me

**Comment by smarthi** [comment]
Very well I'll merge the name to master

**Comment by smarthi** [comment]
I can't get any of the dals (H2O, Spark or Flink) to pass on Mac OpenJDK with this fix, not sure we wanna push this until we have others confirm on both Mac and Linux.

**Comment by andrewpalumbo** [comment]
Sounds good.

-------- Original message --------

**Comment by smarthi** [comment]
So it does indeed pass on Fedora Linux with OpenJDK 8, but fails on Mac OSX.

**Comment by smarthi** [comment]
The dals failures seem local to my Mac and its failing now even without the change, I guess this PR is good to go, merging it.

**Comment by smarthi** [comment]
I don't think this fixed it, Jenkins broken post this fix. Its best to change the javadocs to read [-0.5, 0.5)

**Comment by andrewpalumbo** [comment]
Yeah it looks like we should revert for now.

**Comment by andrewpalumbo** [comment]
It failed in travis also... hadn't noticed that:
```
- dals *** FAILED ***
  9043.008205882092 was not less than 0.15 (DistributedDecompositionsSuiteBase.scala:215)
```

**Comment by andrewpalumbo** [comment]
@dlyubimov do you have any thoughts on why this might fail for `dals` only and only on certain java distributions?

**Comment by andrewpalumbo** [comment]
reverted in master by 0d6c4e02409a6f8da776d00dc661fd178a7630b2

**Comment by andrewmusselman** [comment]
Should this stay open or be closed?

**Comment by smarthi** [comment]
Close it, too risky a fix and it's not easy to reproduce

**Pull request closed without merging**
