### PR TITLE
MAHOUT-1973

### PR DESCRIPTION
**Pull request by AdityaAS**
[BF] Bug Fix
Fixed the hadoop2 related error mentioned in issue MAHOUT-1973

### Purpose of PR:
Please give a short description of what this PR is for.

### Important ToDos
Please mark each with an "x"
- [ ] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/ZEPPELIN/]
- [ ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ ] Created unit tests where appropriate
- [ ] Added licenses correct on newly added files
- [ ] Assigned JIRA to self
- [ ] Added documentation in scala docs/java docs, and to website
- [ ] Successfully built and ran all unit tests, verified that all tests pass locally.

If all of these things aren't complete, but you still feel it is
appropriate to open a PR, please add [WIP] after MAHOUT-XXXX before the
descriptions- e.g. "MAHOUT-XXXX [WIP] Description of Change"

Does this change break earlier versions?

Is this the beginning of a larger project for which a feature branch should be made?

### CODE REVIEW

**Comment by rawkintrevo** [comment]
Hey @AdityaAS thanks for the contribution. 

if you wouldn't mind, please also update `.travis.yml` line 37 adds `-Phadoop2` to all profiles. If this works as expected, that should no longer be necessary.

**Comment by AdityaAS** [comment]
@rawkintrevo  I changed the .travis.yml file and pushed it.. I thought I'd be able to squash the commits on github but haven't found how to. Would really appreciate some help.

**Comment by rawkintrevo** [comment]
This is a very curious case. 

@andrewpalumbo would you take a look? It's only failing on the viennaCL profiles. Perhaps this is related to (would be resolved by) the work you are doing wrt the Scala 2.11 clean up for the viennaCL files?

**Comment by andrewpalumbo** [comment]
Willdo, having trouble logging on to github this morning... (not sure why they logged me out).



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by rawkintrevo** [comment]
@AdityaAS  go ahead and close this please.

**Pull request closed without merging**
