### PR TITLE
MAHOUT-2158 Website Refactor

### PR DESCRIPTION
**Pull request by rawkintrevo**
### Purpose of PR:

Big PR ~~to make sure trevor has the most lines of code committed~~ refactor the website

### Important ToDos
Please mark each with an "x"
- [x] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/mahout/]
- [x] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [x] Added licenses correct on newly added files
- [x] Assigned JIRA to self

Does this change break earlier versions?
No

Is this the beginning of a larger project for which a feature branch should be made?
Maybe

### CODE REVIEW

**Comment by andrewmusselman** [comment]
@rawkintrevo I am trying to build the site locally but am having trouble updating jekyll; did you have to do anything special?

$ bundle exec jekyll serve
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
$ bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
You have requested:
  jekyll = 4.3.2

The bundle currently has jekyll locked at 3.5.0.
Try running `bundle update jekyll`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
$ bundle update jekyll
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (= 4.3.2)

    jekyll-feed (~> 0.6) was resolved to 0.11.0, which depends on
      jekyll (~> 3.3)
$ bundle exec jekyll serve
bundler: command not found: jekyll
Install missing gem executables with `bundle install`

**Comment by rawkintrevo** [comment]
I bumped the Jekyll version. Per the error:

> You have requested:
jekyll = 4.3.2
The bundle currently has jekyll locked at 3.5.0.
Try running bundle update jekyll

**Review by andrewmusselman — APPROVED** [review]
Aside from my own personal issues getting `eventmachine` installed for `jekyll` this looks great

**Comment by rawkintrevo** [comment]
@andrewmusselman give it another look with the last changes- if gtg, ill squash merge

**Review by andrewmusselman — APPROVED** [review]
Ship it

**Pull request merged**
