### PR TITLE
MAHOUT-1762 Utilize spark-submit in bin/mahout script

### PR DESCRIPTION
**Pull request by rawkintrevo**

### CODE REVIEW

**Comment by pferrel** [comment]
@rawkintrevo the real problem is missing classes from the dependency-reduced jar, right? How does this solve that?

**Comment by rawkintrevo** [comment]
@pferrel no, the real problem was that the classes were not being shipped out to the cluster.  This solves by leveraging spark-submit to ship jars.

**Comment by rawkintrevo** [comment]
closing this

**Comment by pferrel** [comment]
Was this added to Mahout?

**Pull request closed without merging**
