### PR TITLE
MAHOUT-1704: Pare down dependency jar for h2o

### PR DESCRIPTION
**Pull request by andrewpalumbo**
This takes the dependency jar for h2o down to ~17M from~68M. Need to verify if this contains all needed deps. I have successfully tested launching {{$mahout h2o-node}} and run $mvn test in parallel on 2 nodes.

### CODE REVIEW

**Comment by andrewpalumbo** [comment]
@avati, could you take a look at this?  I think that we will have to supply other mahout classes to `h2o-node` in `bin\mahout` or elsewhere.

**Comment by andrewpalumbo** [comment]
Added scala libraries into dependency jar.  This bumps the size up to 20M. H2O Tests are passing in parallel now.

**Comment by avati** [comment]
Will look into this soon

**Comment by andrewpalumbo** [comment]
thx.  Should be good. removed scala-reflect. this brings the dependency jar down to ~17M. Tests are passing in parallel.

**Comment by andrewpalumbo** [comment]
this tests fine in parallel.  I'm going to clean it up and push it this afternoon if there are no objections.

**Pull request closed without merging**
