### PR TITLE
MAHOUT-1653-1.1.1: get code ready for spark 1.3

### PR DESCRIPTION
**Pull request by andrewpalumbo**
This patch gets the `spark` module ready for 1.3 and is compatible with spark 1.1.1.

### CODE REVIEW

**Comment by dlyubimov** [comment]
let's merge it to spark-1.3 branch as ongoing effort...

**Comment by andrewpalumbo** [comment]
sounds like a plan.

**Comment by andrewpalumbo** [comment]
My plan for this was to branch just before the code freeze and apply it then so we don't have to keep 2 branches in sync.

**Comment by andrewpalumbo** [comment]
closing- too far out of synch open another PR soon.

**Pull request closed without merging**
